#!/usr/bin/env bash
# Manage the third-party git submodules of airplay-core.
#
#   tools/third-party.sh status                      pinned commit / tag / date per component + how far behind upstream
#   tools/third-party.sh update <name> [<ref>]       move a submodule to <ref> (tag, branch, sha; default: upstream default branch),
#                                                    verify the UxPlay patches still apply, regenerate VERSIONS.md
#   tools/third-party.sh verify-patches              apply patches/UxPlay/*.patch onto the pinned UxPlay in a temp dir
#   tools/third-party.sh versions                    regenerate third_party/VERSIONS.md only
#   tools/third-party.sh rebase-patches              interactive help: when patches no longer apply, opens a scratch
#                                                    checkout with the applicable patches applied so you can fix the rest
#
# Components: UxPlay  libplist  openssl-cmake  ffmpeg      (see .gitmodules)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CPP="$ROOT/airplay-core/src/main/cpp"
TP="$CPP/third_party"
PATCHES="$CPP/patches/UxPlay"
VERSIONS_MD="$TP/VERSIONS.md"
NOTICE="$ROOT/NOTICE.md"
COMPONENTS=(UxPlay libplist openssl-cmake ffmpeg)

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

component_dir() {
  local d="$TP/$1"
  [[ -d "$d/.git" || -f "$d/.git" ]] || die "unknown or uninitialised component '$1' — run: git submodule update --init --recursive"
  printf '%s' "$d"
}

sub_url() { git -C "$ROOT" config -f .gitmodules "submodule.airplay-core/src/main/cpp/third_party/$1.url"; }

# Human-readable version of the pinned commit. Must not depend on which tags happen to be fetched locally
# (CI checks out shallow submodules without tags), so: exact local tag → tag on the remote pointing at HEAD →
# short sha. Remote lookups are cached per run and skipped when offline.
_DESCRIBE_CACHE="$(mktemp)"; trap 'rm -f "$_DESCRIBE_CACHE"' EXIT
describe() {
  local d="$1" head v
  head="$(git -C "$d" rev-parse HEAD)"
  v="$(awk -v h="$head" '$1 == h { print $2; exit }' "$_DESCRIBE_CACHE")"
  if [[ -n "$v" ]]; then printf '%s' "$v"; return; fi
  v="$(git -C "$d" describe --tags --exact-match 2>/dev/null)" || v=""
  if [[ -z "$v" ]]; then
    # peeled refs (^{}) resolve annotated tags to the commit they point at
    v="$(git -C "$d" ls-remote -q --tags origin 2>/dev/null \
        | awk -v h="$head" '$1 == h { t=$2; sub("refs/tags/","",t); sub("\\^\\{\\}$","",t); print t }' \
        | sort -V | tail -1)" || v=""
  fi
  [[ -n "$v" ]] || v="$(git -C "$d" rev-parse --short HEAD)"
  echo "$head $v" >> "$_DESCRIBE_CACHE"
  printf '%s' "$v"
}

ensure_tags() { git -C "$1" fetch -q --tags --depth 1 origin 2>/dev/null || true; }

# ------------------------------------------------------------------------------------------------------------------
verify_patches() {
  local src="$TP/UxPlay" tmp
  [[ -f "$src/lib/raop.c" ]] || die "UxPlay submodule is empty"
  tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' RETURN
  cp -R "$src/lib" "$tmp/"
  local ok=0 total=0
  for p in "$PATCHES"/*.patch; do
    total=$((total + 1))
    if GIT_DIR="$tmp/.nogit" git -C "$tmp" apply --unidiff-zero --directory=lib -p2 "$p" 2>"$tmp/err"; then
      printf '  ok    %s\n' "$(basename "$p")"; ok=$((ok + 1))
    else
      printf '  FAIL  %s\n        %s\n' "$(basename "$p")" "$(head -1 "$tmp/err")"
    fi
  done
  if (( ok != total )); then
    die "$((total - ok))/$total UxPlay patches do not apply onto $(git -C "$src" rev-parse --short HEAD). Run: $0 rebase-patches"
  fi
  say "all $total UxPlay patches apply onto $(describe "$src")"
}

# ------------------------------------------------------------------------------------------------------------------
write_versions() {
  say "writing $(realpath --relative-to="$ROOT" "$VERSIONS_MD" 2>/dev/null || echo third_party/VERSIONS.md)"
  {
    echo "# Third-party versions"
    echo
    echo "Generated by \`tools/third-party.sh versions\` — do not edit by hand. Pinned as git submodules; bump with"
    echo "\`tools/third-party.sh update <component> <ref>\`."
    echo
    echo "| Component | Version | Commit | Date | Upstream |"
    echo "|-----------|---------|--------|------|----------|"
    for c in "${COMPONENTS[@]}"; do
      local d; d="$(component_dir "$c")"
      local sha date ver url
      sha="$(git -C "$d" rev-parse --short=12 HEAD)"
      date="$(git -C "$d" log -1 --format=%cs HEAD)"
      ver="$(describe "$d")"
      url="$(sub_url "$c")"; url="${url%.git}"
      echo "| $c | \`$ver\` | [\`$sha\`]($url/commit/$(git -C "$d" rev-parse HEAD)) | $date | <$url> |"
    done
    echo
    echo "## Local patches"
    echo
    echo "Applied at CMake configure time onto a copy of \`UxPlay/lib\` (\`cmake/PatchUxPlay.cmake\`); the submodule stays pristine."
    echo
    for p in "$PATCHES"/*.patch; do
      # plain diffs carry no Subject:, so derive a title from the file name (0001-fix-foo-bar → fix foo bar)
      local title files
      title="$(basename "$p" .patch | sed -E 's/^[0-9]+-//; s/-/ /g')"
      files="$(grep '^+++ b/' "$p" | sed 's|^+++ b/||' | sort -u | tr '\n' ' ' | sed 's/ $//; s/ /, /g')"
      echo "- \`$(basename "$p")\` — $title (\`$files\`)"
    done
    echo
    echo "OpenSSL itself (\`OPENSSL_BUILD_VERSION\` in \`CMakeLists.txt\`): $(grep -o 'OPENSSL_BUILD_VERSION "[^"]*"' "$CPP/CMakeLists.txt" | cut -d'"' -f2)"
  } > "$VERSIONS_MD"
}

# ------------------------------------------------------------------------------------------------------------------
cmd_status() {
  printf '%-14s %-24s %-13s %-11s %s\n' COMPONENT VERSION COMMIT DATE BEHIND
  for c in "${COMPONENTS[@]}"; do
    local d; d="$(component_dir "$c")"
    ensure_tags "$d"
    local head; head="$(git -C "$d" rev-parse HEAD)"
    local remote_head branch behind="?"
    branch="$(git -C "$d" symbolic-ref -q --short refs/remotes/origin/HEAD 2>/dev/null | sed 's|origin/||')" || true
    [[ -n "$branch" ]] || branch="$(git -C "$d" ls-remote -q --symref origin HEAD 2>/dev/null | awk '/^ref:/ {sub("refs/heads/","",$2); print $2}')" || true
    if [[ -n "$branch" ]]; then
      remote_head="$(git -C "$d" ls-remote -q origin "refs/heads/$branch" 2>/dev/null | cut -f1)"
      if [[ "$remote_head" == "$head" ]]; then behind="up to date ($branch)"
      elif [[ -n "$remote_head" ]]; then behind="$branch @ ${remote_head:0:7}"; fi
    fi
    # newest release-looking tag: strip a leading v/n, drop pre-releases, sort by version
    local newest_tag
    newest_tag="$(git -C "$d" ls-remote -q --tags --refs origin 2>/dev/null | awk -F/ '{print $NF}' \
      | grep -Ev 'rc|beta|alpha|dev|pre' | grep -E '^[vn]?[0-9]+(\.[0-9]+)+$' \
      | sed -E 's/^([vn]?)(.*)$/\2 \1\2/' | sort -V | tail -1 | cut -d' ' -f2)" || true
    printf '%-14s %-24s %-13s %-11s %s%s\n' "$c" "$(describe "$d")" "${head:0:12}" "$(git -C "$d" log -1 --format=%cs)" "$behind" "${newest_tag:+ · newest tag $newest_tag}"
  done
  echo
  git -C "$ROOT" submodule status | grep -q '^[+-]' && warn "submodule working trees differ from the commits recorded in the repo (git submodule status)" || true
}

cmd_update() {
  local c="${1:-}"; local ref="${2:-}"
  [[ -n "$c" ]] || die "usage: $0 update <component> [<ref>]"
  local d; d="$(component_dir "$c")"
  local before; before="$(describe "$d")"
  say "fetching $c"
  git -C "$d" fetch -q --tags origin
  if [[ -z "$ref" ]]; then
    ref="$(git -C "$d" remote show origin | awk '/HEAD branch/ {print $NF}')"
    ref="origin/$ref"
  elif git -C "$d" rev-parse -q --verify "refs/tags/$ref" >/dev/null; then :
  elif git -C "$d" ls-remote -q --exit-code origin "refs/heads/$ref" >/dev/null 2>&1; then
    git -C "$d" fetch -q origin "$ref"; ref="origin/$ref"
  else
    git -C "$d" fetch -q origin "$ref" 2>/dev/null || true   # bare sha not reachable from a shallow clone
  fi
  git -C "$d" checkout -q --detach "$ref" || die "cannot check out '$ref' in $c"
  say "$c: $before → $(describe "$d")  ($(git -C "$d" log -1 --format='%cs %s' | cut -c1-90))"
  if [[ "$c" == UxPlay ]]; then
    verify_patches || { warn "UxPlay moved but patches are broken — fix them or run: git -C $d checkout $(git -C "$ROOT" rev-parse "HEAD:airplay-core/src/main/cpp/third_party/UxPlay")"; exit 1; }
  fi
  write_versions
  echo
  echo "Next: build & test (./gradlew :airplay-core:assembleRelease), then:"
  echo "  git add airplay-core/src/main/cpp/third_party/$c $VERSIONS_MD && git commit -m \"third_party: $c $before → $(describe "$d")\""
}

cmd_rebase_patches() {
  local src="$TP/UxPlay" work="$ROOT/build/uxplay-rebase"
  rm -rf "$work"; mkdir -p "$(dirname "$work")"
  git clone -q --shared "$src" "$work"
  git -C "$work" checkout -q --detach "$(git -C "$src" rev-parse HEAD)"
  say "scratch checkout: $work"
  for p in "$PATCHES"/*.patch; do
    if git -C "$work" apply --unidiff-zero --index "$p" 2>/dev/null; then
      git -C "$work" -c user.name=rebase -c user.email=rebase@local commit -q -m "$(basename "$p" .patch)"
      echo "  applied   $(basename "$p")"
    else
      echo "  CONFLICT  $(basename "$p") — fix by hand in $work, then regenerate with:"
      echo "            git -C $work add -A && git -C $work commit -m '$(basename "$p" .patch)'"
    fi
  done
  echo
  echo "When every patch is committed in the scratch repo, export the series back with:"
  echo "  git -C $work format-patch --unidiff-zero --no-signature --zero-commit -o $PATCHES \$(git -C $src rev-parse HEAD)"
  echo "  (remove the old .patch files first), then: $0 verify-patches"
}

case "${1:-}" in
  status)          cmd_status ;;
  update)          shift; cmd_update "$@" ;;
  verify-patches)  verify_patches ;;
  versions)        write_versions ;;
  rebase-patches)  cmd_rebase_patches ;;
  *) sed -n '2,13p' "$0" | sed 's/^# \{0,1\}//'; exit 2 ;;
esac
